{
	"Translated By": "Fares AlBelady",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; المكان الذي يجتمع فيه المطورون.",
	"Integrations": "التكامل",
	"Pricing": "الأسعار",
	"Apps": "التطبيقات",
	"Sign In to Start Talking": "سجّل دخولك لتبدأ التحدّث",
	"login": "تسجيل الدخول",
	"API": "الواجهة البرمجية",
	"Blog": "المدونة",
	"Twitter": "تويتر",
	"Support": "الدعم الفني",

	"Where communities thrive": "المكان الذي تنمو فيه المجتمعات",
	"Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter هو خدمة رسائل صوتية، وشبكية، تُساعد على إدارة ونمو واتصال المجتمعات عن طريق المراسلة، والمحتوى، والاستكشاف.",
	"Create your own community": "أنشئ مجتمعك",
	"Explore other communities": "استكشف المجتمعات الأخرى",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "بتسجيلك، أنت توافق على <a %s>الأحكام والشروط</a>",
	"Free without limits": "مجّاني، بشكلٍ لا محدود",
	"Enjoy free public communities with unlimited people, message history and integrations.": "استمتع بالمجتمعات المجانية، بعددٍ لا محدود من الأشخاص، والرسائل، والخدمات التكاملية",
	"Simple to create": "إنشاؤه بسيط",
	"Simply create your community and start talking - no need to set up any invitation services.": "ببساطة، أنشئ مجتمعك، وابدأ التحدث - لا تحتاج لإعداد أي من خدمات الدعوة",
	"Quick to grow": "سريع النمو",
	"Grow your community in no time with our easy sharing tools.": "نمّي مجتمعك، بدون تضييع وقت، بواسطة أدوات المشاركة السهلة.",
	"Out in the open": "في العراء",
	"Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "لتجعل مجتمعك مُستكشفًا! مع  Gitter، الكل يستطيع إيجاد مجتمعك عبر خدمتنا أو محرّكات البحث.",

	"Trusted by": "وَثِق به",
	"Some of our communities": "بعض مجتمعاتنا",
	"Create your own": "أنشئ لك واحدًا",
	"Explore rooms": "استكشف الغرف",
	"Explore": "استكشف",
	"GitterHQ": "GitterHQ",
	"Let’s talk about Gitter!": "لنتحدّث عن Gitter!",

	"Designed for community collaboration": "مصمم للتعاون الاجتماعي",
	"Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.",
	"We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.",

	"Loved by our users": "عُشق من مستخدمينا",
	"Gitter is nothing without the people using it day in and day out.": "Gitter is nothing without the people using it day in and day out.",
	"We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.",

	"Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.",
	"Free": "مجانًا",
	"Forever": "للأبد",
	"<b>Unlimited</b> chat history": "تاريخ المراسلة بشكل <b>غير محدود</b>",
	"<b>Unlimited</b> integrations": "تكامل <b>غير محدود</b>",
	"<b>Unlimited</b> public rooms": "غرف عامة <b>غير محدودة</b>",
	"<b>Unlimited</b> private rooms": "غرف خاصة <b>غير محدودة</b>",
	"Limited to 25 users per private room": "محدود بـ 25 مستخدم لكل غرفة خاصة",
	"<b>Get started</b> for free": "<b>ابدأ الآن</b> مجانًا",
	"Premium Plans": "الخطط المميّزة",
	"starting from": "تبدأ من",
	"per month": "لكل شهر",
	"Community <b>insights</b> & analytics": "Community <b>insights</b> & analytics",
	"Community <b>engagement</b> & marketing tools": "Community <b>engagement</b> & marketing tools",
	"<b>Customisable look</b> of the community rooms": "<b>Customisable look</b> of the community rooms",
	"<b>PR & promotional</b> tools": "<b>PR & promotional</b> tools",
	"Access to <b>community managers</b>": "الذهان إلى<b>مديري المجتمع</b>",
	"<b>Join</b> earlybird programme": "<b>Join</b> earlybird programme",

	"Get Gitter now!": "احصل على Gitter الآن!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter is available in all modern browsers as well as apps for desktops and mobile phones.",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>",
	"Mac": "ماكنتوش",
	"Windows": "ويندوز",
	"Linux 32": "لينكس 32",
	"Linux 64": "لينكس 64",
	"iPhone": "آيفون",
	"Android": "أندرويد"
}
