{
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Където разработчиците се събират да разговарят.",
	"Integrations": "Интеграции",
	"Pricing": "Ценообразуване",
	"Apps": "Приложения",
	"Sign In to Start Talking": "Влезте в профила си, за да започнете разговор",
	"login": "вход",
	"API": "API",
	"Blog": "Блог",
	"Twitter": "Twitter",
	"Support": "Поддръжка",

	"Where communities thrive": "Къде общностите процъфтяват",
	"Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter е чат и мрежова платформа, която помага да се управляват, нарастват и свързват общности чрез съобщения, съдържание и откритие.",
	"Create your own community": "Създайте своя собствена общност",
	"Explore other communities": "Разгледайте други общности",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "Като се регистрирате вие се съгласявате с нашата <a %s>Правила и условия</a>",
	"Free without limits": "Безплатна без граници",
	"Enjoy free public communities with unlimited people, message history and integrations.": "Насладете се на безплатни публични общности с неограничени хора, история на съобщенията и интеграции.",
	"Simple to create": "Просто за създаване",
	"Simply create your community and start talking - no need to set up any invitation services.": "Просто създайте вашата общност и започнете разговор - не е необходимо да създавате покани.",
	"Quick to grow": "Бързо за нарастване",
	"Grow your community in no time with our easy sharing tools.": "Увеличете вашата общност за нула време с нашите инструменти за споделяне.",
	"Out in the open": "На открито",
	"Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "Нека вашата общност бъде открита! С Gitter, всеки може да намери своята общност в нашата директория или чрез търсачките.",

	"Trusted by": "Те ни се довериха",
	"Some of our communities": "Някои от нашите общности",
	"Create your own": "Създайте своя собствена",
	"Explore rooms": "Разгледайте стаи",
	"Explore": "Разгледай",
	"GitterHQ": "GitterHQ",
	"Let’s talk about Gitter!": "Да поговорим за Gitter!",

	"Designed for community collaboration": "Проектиран за сътрудничество на общността",
	"Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "Gitter има за цел да направи изпращането на съобщения, сътрудничеството и откриването толкова гладко и лесно, колкото е възможно да бъде. Можете лесно да създавате, организирате и увеличите вашите общности, да каните други хора да се присъединят само с едно кликване.",
	"We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Ние също така предоставяме интеграции с GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. Приемаме поръчкови уеб куки, имаме <a %s>хранилище с отворен код</a> за интеграции както и <a %s>гъвкаво API</a>.",

	"Loved by our users": "Обичан от нашите потребители",
	"Gitter is nothing without the people using it day in and day out.": "Gitter е нищо без хората, използвайки го ден след ден.",
	"We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Попитахме няколко човека какво означава Gitter за тях, това е каквото те казаха. Ако обичате Gitter, напишете туит <a %s>%s</a> и ние ще актуализираме тези цитати всеки месец.",

	"Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "Ценовите планове идват рано през 2017. Присъединете се към ранната програма и получете 75%% отстъпка.",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Цените могат да се облагат с ДДС. Като се регистрирате вие се съгласявате с нашите <a %s>Правила и условия</a>.",
	"Free": "Безплатно",
	"Forever": "Завинаги",
	"<b>Unlimited</b> chat history": "<b>Неограничена</b> чат история",
	"<b>Unlimited</b> integrations": "<b>Неограничени</b> интеграции",
	"<b>Unlimited</b> public rooms": "<b>Неограничени</b> публични стаи",
	"<b>Unlimited</b> private rooms": "<b>Неограничени</b> частни стаи",
	"Limited to 25 users per private room": "Ограничение от 25 потребители за частна стая",
	"<b>Get started</b> for free": "<b>Започнете</b> безплатно",
	"Premium Plans": "Платени планове",
	"starting from": "започвайки от",
	"per month": "за месец",
	"Community <b>insights</b> & analytics": "Обществени <b>статистики</b> & анализи",
	"Community <b>engagement</b> & marketing tools": "Обществена <b>ангажираност</b> & маркетингови инструменти",
	"<b>Customisable look</b> of the community rooms": "<b>Персонален изглед</b> от стаите за общността",
	"<b>PR & promotional</b> tools": "<b>PR & промоционални</b> инструменти",
	"Access to <b>community managers</b>": "Достъп до <b>мениджъри на общността</b>",
	"<b>Join</b> earlybird programme": "<b>Присъедини се</b> към ранната програма",

	"Get Gitter now!": "Вземи Gitter сега!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter е на разположение на всички съвременни браузъри, както и приложения за настолни компютри и мобилни телефони.",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "В момента имаме приложения за OSX, iOS, Android, Windows и Linux. Също така имаме и сладко малко <a %s>IRC мостче</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android"
}
