{
	"Integrations": "Integrace",
	"Pricing": "Ceny",
	"Apps": "Aplikace",
	"Existing user login": "Existující uživatelský účet",
	"login": "přihlášení",
	"Chat, for GitHub.": "Chat, pro GitHub.",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "Získejte neomezené veřejné místnosti a one-to-one chaty, navždy zdarma. Soukromé týmové plány začínají od $2 za uživatele měsíčně. Kreditní karta není vyžadována.",
	"Sign up free with Github": "Zaregistrujte se zdarma s GitHubem",
	"Sign up with Github": "Zaregistrujte se s GitHubem",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "Registrací souhlasíte s našimi <a %s>Všeobecnými smluvními podmínkami</a>",
	"Markdown power": "Síla Markdownu",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "Chtěli jste někdy plnou podporu markdown v chatu? A co zvýrazdňování syntaxe?",
	"Yip, we got your back.": "Yip, we got your back.",
	"Private conversations": "Soukromé konverzace",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Veřejné místnosti jsou super (a zdarma), ale víme, že některé věci jsou soukromé. Takže máme <a %s>plány pro toto</a>.",
	"Developer friendly": "Přátelské pro vývojáře",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "Tohle je obrázek mraku na pozadí mraků. OMG! <a %s>Začleňujeme</a> hromadu věcí v kloudu.",
	"Some of our communities": "Některé z našich komunit",
	"Create your own": "Vytvoř svou vlastní",
	"Explore rooms": "Prozkoumej místnosti",
	"Explore": "Prozkoumat",
	"Integrated with your workflow": "Integruj se svým pracovním postupem",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter je postaven na vrholu GitHubu a je úzce spojen s vašemi organizacemi, repozitáři, problémy a aktivitou.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Nabízíme integraci s Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. Také přijímáme vlastní webhooks, máme <a %s>open source repozotář</a> pro integrace tak jako <a %s>flexibilní API</a>.",
	"Loved by our users": "Milováno našimi uživateli",
	"Gitter is nothing without the people using it day in and day out.": "Gitter není nic bez lidí používajících jej den co den.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Zeptali jsme skupini lidí, co pro ně Gitter znamená, to je to co museli říct. Pokud milujete Gitter, Tweetněte nás <a %s>%s</a> a my budeme vylepšovat tyto citace každý měsíc.",
	"Personal pricing": "Ceny pro jednotlivce",
	"Free": "Zdarma",
	"Forever": "Navždy",
	"<b>Unlimited</b> public rooms": "<b>Neomezené</b> veřejné místnosti",
	"<b>1</b> private room": "<b>1</b> soukromá místnost",
	"<b>2 weeks’</b> chat history": "<b>2 týdny’</b> historie chatu",
	"<b>Get started</b> for free": "<b>Začněte</b> zdarma",
	"Individual": "Individuální",
	"monthly": "měsíčně",
	"<b>Unlimited</b> private rooms": "<b>Neomezené</b> privatní místnosti",
	"<b>Unlimited</b> chat history": "<b>Neomezená</b> historie chatu",
	"<b>Purchase</b> now": "<b>Kup</b> dnes",
	"Organisation pricing": "Ceny pro organizace",
	"Bronze": "Bronz",
	"per user/month": "za uživatele/měsíc",
	"<b>6 months’</b> chat history": "<b>6 měsíců’</b> historie chatu",
	"Silver": "Stříbro",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Náš plán zdarma zahrnuje jednu provátní místnost na organizaci ke které patříte na GitHubu",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Náš individuální plán dovoluje vytvářet soukromé místnosti využitím vašeho soukromého účtu jako vlastník",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Náš plán pro organizace dovoluje vytvářet soukromé s využitím vašeho GitHub účtu organizace jako vlastník",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Ceny mohou být předmětem DPH. Registrací souhlasíte s <a %s>Všeobecnými smluvními podmínkami</a>.",
	"Get Gitter now!": "Získej Gitter teď!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter je dostupný ve všech moderních prohlížečích tak jako v aplikaci pro stolní počítače a mobilní telefony.",
	"We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>": "Aktuálně máme aplikaci pro OSX, iOS, Android a Windows a aplikace pro Linux příjde brzy. Také máme slatký malý <a %s>IRC most</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Coming soon": "Již brzy",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "Od vývojářů, pro vývojáře",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter je vybudován v Londýně týmem vývojářů podobných jako vy. Sakra i ten chlápek od produktů píše kódy, avšak obvykle skončíme přepisování těchto kousků.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "Pokud někdy budete kolem Silicon Roundabout, dejte nám vědět, máme rádi setkání s ostatními vývojáři.",
	"Support": "Podpora",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Kam developeři chodí hovořit.",
	"Translated By": "Honza Bittner (www.honzabittner.cz)"
}
