{
	"Integrations": "Integrations",
	"Pricing": "Pricing",
	"Apps": "Apps",
	"Existing user login": "Existing user login",
	"login": "login",
	"Chat, for GitHub.": "Chat, for GitHub.",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.",
	"Sign up free with Github": "Sign up free with Github",
	"Sign up with Github": "Sign up with Github",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "By signing up you agree to our <a %s>Terms and Conditions</a>",
	"Markdown power": "Markdown power",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "Ever wanted full markdown support in chat? How about syntax highlighting?",
	"Yip, we got your back.": "Yip, we got your back.",
	"Private conversations": "Private conversations",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.",
	"Developer friendly": "Developer friendly",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.",
	"Some of our communities": "Some of our communities",
	"Create your own": "Create your own",
	"Explore rooms": "Explore rooms",
	"Explore": "Explore",
	"Integrated with your workflow": "Integrated with your workflow",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.",
	"Loved by our users": "Loved by our users",
	"Gitter is nothing without the people using it day in and day out.": "Gitter is nothing without the people using it day in and day out.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.",
	"Personal pricing": "Personal pricing",
	"Free": "Free",
	"Forever": "Forever",
	"<b>Unlimited</b> public rooms": "<b>Unlimited</b> public rooms",
	"<b>1</b> private room": "<b>1</b> private room",
	"<b>2 weeks’</b> chat history": "<b>2 weeks’</b> chat history",
	"<b>Get started</b> for free": "<b>Get started</b> for free",
	"Individual": "Individual",
	"monthly": "monthly",
	"<b>Unlimited</b> private rooms": "<b>Unlimited</b> private rooms",
	"<b>Unlimited</b> chat history": "<b>Unlimited</b> chat history",
	"<b>Purchase</b> now": "<b>Purchase</b> now",
	"Organisation pricing": "Organisation pricing",
	"Bronze": "Bronze",
	"per user/month": "per user/month",
	"<b>6 months’</b> chat history": "<b>6 months’</b> chat history",
	"Silver": "Silver",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Our free plan includes one private room per organisation you belong to on GitHub",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Our Individual plan allows you to create private rooms using your personal account as the owner",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Our organisation plans allow you to create private rooms using your GitHub organisation as the owner",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.",
	"Get Gitter now!": "Get Gitter now!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter is available in all modern browsers as well as apps for desktops and mobile phones.",
	"We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>": "We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Coming soon": "Coming soon",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "By developers, for developers",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.",
	"Support": "Support",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Where developers come to talk.",
	"Translated By": "Translated By"
}