{
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Where developers come to talk.",
	"Integrations": "Integrations",
	"Pricing": "Pricing",
	"Apps": "Apps",
	"Sign In to Start Talking": "Sign In to Start Talking",
	"login": "login",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Support": "Support",

	"Where communities thrive": "Where communities thrive",
	"Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.",
	"Create your own community": "Create your own community",
	"Explore other communities": "Explore other communities",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "By signing up you agree to our <a %s>Terms and Conditions</a>",
	"Free without limits": "Free without limits",
	"Enjoy free public communities with unlimited people, message history and integrations.": "Enjoy free public communities with unlimited people, message history and integrations.",
	"Simple to create": "Simple to create",
	"Simply create your community and start talking - no need to set up any invitation services.": "Simply create your community and start talking - no need to set up any invitation services.",
	"Quick to grow": "Quick to grow",
	"Grow your community in no time with our easy sharing tools.": "Grow your community in no time with our easy sharing tools.",
	"Out in the open": "Out in the open",
	"Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.",

	"Trusted by": "Trusted by",
	"Some of our communities": "Some of our communities",
	"Create your own": "Create your own",
	"Explore rooms": "Explore rooms",
	"Explore": "Explore",
	"GitterHQ": "GitterHQ",
	"Let’s talk about Gitter!": "Let’s talk about Gitter!",

	"Designed for community collaboration": "Designed for community collaboration",
	"Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.",
	"We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.",

	"Loved by our users": "Loved by our users",
	"Gitter is nothing without the people using it day in and day out.": "Gitter is nothing without the people using it day in and day out.",
	"We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.",

	"Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.",
	"Free": "Free",
	"Forever": "Forever",
	"<b>Unlimited</b> chat history": "<b>Unlimited</b> chat history",
	"<b>Unlimited</b> integrations": "<b>Unlimited</b> integrations",
	"<b>Unlimited</b> public rooms": "<b>Unlimited</b> public rooms",
	"<b>Unlimited</b> private rooms": "<b>Unlimited</b> private rooms",
	"Limited to 25 users per private room": "Limited to 25 users per private room",
	"<b>Get started</b> for free": "<b>Get started</b> for free",
	"Premium Plans": "Premium Plans",
	"starting from": "starting from",
	"per month": "per month",
	"Community <b>insights</b> & analytics": "Community <b>insights</b> & analytics",
	"Community <b>engagement</b> & marketing tools": "Community <b>engagement</b> & marketing tools",
	"<b>Customisable look</b> of the community rooms": "<b>Customisable look</b> of the community rooms",
	"<b>PR & promotional</b> tools": "<b>PR & promotional</b> tools",
	"Access to <b>community managers</b>": "Access to <b>community managers</b>",
	"<b>Join</b> earlybird programme": "<b>Join</b> earlybird programme",

	"Get Gitter now!": "Get Gitter now!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter is available in all modern browsers as well as apps for desktops and mobile phones.",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android"
}
