{
	"Integrations": "Integraciones",
	"Pricing": "Precios",
	"Apps": "Apps",
	"Existing user login": "Iniciar sesión",
	"login": "Iniciar sesión",
	"Chat, for GitHub.": "Chat, para GitHub.",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "Salas públicas y conversaciones uno-a-uno ilimitadas, para siempre. Planes para equipos desde $2 por usuario por mes. No requiere tarjeta de crédito.",
	"Sign up free with Github": "Regístrate gratis con Github",
	"Sign up with Github": "Regístrate con Github",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "Registrándote aceptas nuestros <a %s>Términos y Condiciones</a>",
	"Markdown power": "Markdown",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "Alguna vez has querido soporte para Markdown en tu chat? Y resaltado de sintaxis?",
	"Yip, we got your back.": "Sip, te tenemos cubierto.",
	"Private conversations": "Privacidad",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Las salas públicas son geniales (y gratis), pero sabemos que a veces necesitas privacidad. Tenemos <a %s>planes para eso</a>.",
	"Developer friendly": "Para desarrolladores",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "Esta es una foto de La Nube con un fondo de nubes. OMG! Nosotros nos <a %s>integramos</a> con un montón de servicios en La Nube.",
	"Some of our communities": "Algunas de nuestras comunidades",
	"Create your own": "Crea tu propia comunidad",
	"Explore rooms": "Explora salas públicas",
	"Explore": "Explora",
	"Integrated with your workflow": "Integrado con tu manera de trabajar",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter esta construido sobre GitHub y se integra perfectamente con tus organizaciones, repositorios, conflictos y actividad.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Proveemos integración con Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. También procesamos webhooks, tenemos un <a %s>repositorios open source</a> de integraciones así como una <a %s>flexible API</a>.",
	"Loved by our users": "Nuestros usuarios",
	"Gitter is nothing without the people using it day in and day out.": "Gitter no es nada sin la gente que lo utiliza a diario.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Les hemos preguntado que significa Gitter para ellos, esto es lo que nos dijeron. Si te gusta Gitter, envíanos un tweet <a %s>%s</a>. Iremos actualizando estas citas cada mes.",
	"Personal pricing": "Personal",
	"Free": "Gratis",
	"Forever": "Para siempre",
	"<b>Unlimited</b> public rooms": "Salas públicas <b>ilimitadas</b>",
	"<b>1</b> private room": "<b>1</b> sala privada",
	"<b>2 weeks’</b> chat history": "<b>2 semanas</b> de histórico de conversaciones",
	"<b>Get started</b> for free": "<b>Regístrate</b> gratis",
	"Individual": "Individual",
	"monthly": "mensual",
	"<b>Unlimited</b> private rooms": "Salas privadas <b>ilimitadas</b>",
	"<b>Unlimited</b> chat history": "Histórico de conversaciones <b>ilimitado</b>",
	"<b>Purchase</b> now": "<b>Contratar</b> ahora",
	"Organisation pricing": "Organizaciones",
	"Bronze": "Bronce",
	"per user/month": "por usuario por mes",
	"<b>6 months’</b> chat history": "<b>6 meses</b> de histórico de conversaciones",
	"Silver": "Platino",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Nuestro plan gratuito incluye una sala privada por organización a la perteneces en GitHub",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Nuestro plan individual te permite crear salas privadas bajo tu nombre",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Nuestros planes para organizaciones te permiten crear salas privadas para estas mismas",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Precios sujetos a VAT. Registrándote aceptas nuestros <a %s>Términos y condiciones</a>.",
	"Get Gitter now!": "Regístrate ahora!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter esta disponible en todos los navegadores modernos así como en aplicaciones de escritorio y móvil.",
	"We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>": "De momento tenemos aplicaciones para OSX, iOS, Android, Windows y Linux. También tenemos una interfaz con <a %s>IRC</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Coming soon": "Muy pronto",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "Para desarrolladores, por desarrolladores",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter se desarrolla en Londres por un equipo de desarrolladores tal y como tú. Incluso el gestor de producto escribe código, pero generalmente reescribimos esos trozos.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "Si alguna vez pasas por Silicon Roundabout, danos el toque, nos encanta conocer otros desarrolladores.",
	"Support": "Soporte",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
  "Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Donde los desarrolladores vienen a conversar.",
	"Translated By": ""
}
