{
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Là où les développeurs viennent discuter",
	"Integrations": "Intégrations",
	"Pricing": "Tarifs",
	"Apps": "Applis",
	"Sign In to Start Talking": "Connectez-vous pour commencer à discuter",
	"login": "Connexion",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Support": "Assistance",

	"Where communities thrive": "Là où les communautés se développent",
	"Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter est une plate-forme de discussion et de réseautage qui permet de gérer, de développer et d'interconnecter des communautés  ",
	"Create your own community": "Créez votre propre communauté",
	"Explore other communities": "Découvrez d'autres communautés",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "En vous inscrivant, vous acceptez nos <a %s>conditions d'utilisation</a>",
	"Free without limits": "Gratuit. Illimité",
	"Enjoy free public communities with unlimited people, message history and integrations.": "",
	"Simple to create": "Créez simplement",
	"Simply create your community and start talking - no need to set up any invitation services.": "Créez votre communauté et commencez à discuter. Tout simplement - sans avoir besoin d'envoyer des invitations.",
	"Quick to grow": "Développez rapidement",
	"Grow your community in no time with our easy sharing tools.": "Grace à nos outils de partage ultra-simples, vous pouvez faire grandir votre communauté en un temps record",
	"Out in the open": "Ouvert sur le monde",
	"Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "Laissez le monde venir à vous! Avec Gitter, tout le monde peut trouver votre communauté dans notre répertoire et via les moteurs de recherches",

	"Trusted by": "Ces entreprises nous font confiance",
	"Some of our communities": "Quelques-unes de nos communautés",
	"Create your own": "Créez la votre",
	"Explore rooms": "Découvrez des espaces de discussion",
	"Explore": "Explorez",
	"GitterHQ": "GitterHQ",
	"Let’s talk about Gitter!": "Parlons de Gitter!",

	"Designed for community collaboration": "",
	"Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "",
	"We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Nous fournissons également des intégrations avec GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. Nous acceptons les custom webhooks et nous avons un repository open source ainsi qu'une <a %s>API flexible</a>.",

	"Loved by our users": "Nos utilisateurs nous adorent",
	"Gitter is nothing without the people using it day in and day out.": "Gitter ne serait rien sans les personnes qui l'utilisent jour après jour.",
	"We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Nous avons demandé à quelques utilisateurs ce qu'ils pensent de Gitter, voici leurs réponses. Si vous aimez Gitter, dites-le nous via Twitter <a %s>%s</a> et nous publierons votre message ici, le mois suivant.",

	"Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "",
	"Free": "Gratuit",
	"Forever": "Pour toujours",
	"<b>Unlimited</b> chat history": "Historique de discussion: <b>illimité</b>",
	"<b>Unlimited</b> integrations": "Nombre d'intégrations: <b>illimité</b>",
	"<b>Unlimited</b> public rooms": "Nombre d'espaces de discussion publics: <b>illimité</b>",
	"<b>Unlimited</b> private rooms": "Nombre d'espaces de discussion privés: <b>illimité</b>",
	"Limited to 25 users per private room": "Limité à 25 utilisateurs par espace de discussion privé",
	"<b>Get started</b> for free": "<b>Inscrivez-vous.</b> C'est gratuit",
	"Premium Plans": "",
	"starting from": "a partir de",
	"per month": "par mois",
	"Community <b>insights</b> & analytics": "",
	"Community <b>engagement</b> & marketing tools": "",
	"<b>Customisable look</b> of the community rooms": "",
	"<b>PR & promotional</b> tools": "",
	"Access to <b>community managers</b>": "",
	"<b>Join</b> earlybird programme": "",

	"Get Gitter now!": "Commencez à utiliser Gitter dès maintenant!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android"
}
