{
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Là où les développeurs viennent discuter",
	"Integrations": "Intégrations",
	"Pricing": "Tarifs",
	"Apps": "Applis",
	"Sign In to Start Talking": "Connectez-vous pour commencer à discuter",
	"login": "Connexion",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Support": "Assistance",

	"Where communities thrive": "",
	"Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "",
	"Create your own community": "",
	"Explore other communities": "",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "",
	"Free without limits": "",
	"Enjoy free public communities with unlimited people, message history and integrations.": "",
	"Simple to create": "",
	"Simply create your community and start talking - no need to set up any invitation services.": "",
	"Quick to grow": "",
	"Grow your community in no time with our easy sharing tools.": "",
	"Out in the open": "",
	"Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "",

	"Trusted by": "",
	"Some of our communities": "",
	"Create your own": "",
	"Explore rooms": "",
	"Explore": "",
	"GitterHQ": "",
	"Let’s talk about Gitter!": "",

	"Designed for community collaboration": "",
	"Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "",
	"We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "",

	"Loved by our users": "",
	"Gitter is nothing without the people using it day in and day out.": "",
	"We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "",

	"Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "",
	"Free": "",
	"Forever": "",
	"<b>Unlimited</b> chat history": "",
	"<b>Unlimited</b> integrations": "",
	"<b>Unlimited</b> public rooms": "",
	"<b>Unlimited</b> private rooms": "",
	"Limited to 25 users per private room": "",
	"<b>Get started</b> for free": "",
	"Premium Plans": "",
	"starting from": "",
	"per month": "",
	"Community <b>insights</b> & analytics": "",
	"Community <b>engagement</b> & marketing tools": "",
	"<b>Customisable look</b> of the community rooms": "",
	"<b>PR & promotional</b> tools": "",
	"Access to <b>community managers</b>": "",
	"<b>Join</b> earlybird programme": "",

	"Get Gitter now!": "",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android"
}
