{
    "Translated By": "<a href='https://github.com/dikiaap' title='Diki Ananta di Github' target='_blank'>Diki Ananta</a>",
    "Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Dimana pengembang datang untuk berbicara.",
    "Integrations": "Integrasi",
    "Pricing": "Harga",
    "Apps": "Aplikasi",
    "Sign In to Start Talking": "Masuk untuk Mulai Berbicara",
    "login": "masuk",
    "API": "API",
    "Blog": "Blog",
    "Twitter": "Twitter",
    "Support": "Bantuan",

    "Where communities thrive": "Dimana komunitas berkembang",
    "Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter adalah platform obrolan dan jaringan yang membantu mengelola, mengembangkan, dan menghubungkan komunitas melalui pesan, konten, dan penemuan.",
    "Create your own community": "Buat komunitas Anda sendiri",
    "Explore other communities": "Jelajahi komunitas lainnya",
    "By signing up you agree to our <a %s>Terms and Conditions</a>": "Dengan mendaftar Anda menyetujui <a %s>Syarat dan Ketentuan</a> kami",
    "Free without limits": "Gratis tanpa batas",
    "Enjoy free public communities with unlimited people, message history and integrations.": "Nikmati komunitas publik gratis dengan orang-orang yang tak ada batasnya, riwayat pesan dan integrasi.",
    "Simple to create": "Mudah dibuat",
    "Simply create your community and start talking - no need to set up any invitation services.": "Cukup buat komunitas Anda dan mulailah berbicara - tidak perlu menyiapkan layanan undangan apa pun.",
    "Quick to grow": "Cepat tumbuh",
    "Grow your community in no time with our easy sharing tools.": "Tingkatkan komunitas Anda dalam waktu singkat dengan alat berbagi yang mudah.",
    "Out in the open": "Keluar di tempat terbuka",
    "Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "Biarkan komunitas Anda ditemukan! Dengan Gitter, semua orang dapat menemukan komunitas Anda di direktori kami dan melalui mesin pencari.",

    "Trusted by": "Dipercaya oleh",
    "Some of our communities": "Beberapa komunitas kami",
    "Create your own": "Buat milik Anda sendiri",
    "Explore rooms": "Jelajahi room",
    "Explore": "Jelajahi",
    "GitterHQ": "GitterHQ",
    "Let’s talk about Gitter!": "Mari berbicara tentang Gitter!",

    "Designed for community collaboration": "Dirancang untuk kolaborasi komunitas",
    "Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "Gitter dirancang untuk perpesanan komunitas, kolaborasi dan penemuan semulus dan sesederhana mungkin. Anda dapat dengan mudah membuat, mengatur dan mengembangkan komunitas Anda, mengundang orang lain untuk bergabung hanya dengan sekali klik.",
    "We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Kami juga menyediakan integrasi dengan GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. Kami menerima modifikasi webhook, memiliki <a %s>repositori sumber terbuka</a> untuk integrasi dan juga <a %s>API fleksibel</a>.",

    "Loved by our users": "Dicintai oleh pengguna kami",
    "Gitter is nothing without the people using it day in and day out.": "Gitter bukanlah apa-apa tanpa orang-orang yang menggunakannya setiap hari.",
    "We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Kami bertanya kepada beberapa orang tentang arti Gitter bagi mereka, inilah yang mereka katakan. Jika Anda menyukai Gitter, Tweet kami <a %s>%s</a> dan kami akan memperbarui kutipan ini setiap bulannya.",

    "Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "Rencana harga akan dimulai awal 2017. Bergabunglah dengan program Earlybird sekarang dan dapatkan diskon 75%%.",
    "Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Harga mungkin dikenakan PPN. Dengan mendaftar Anda menyetujui <a %s>Syarat dan Ketentuan</a> kami.",
    "Free": "Gratis",
    "Forever": "Selamanya",
    "<b>Unlimited</b> chat history": "Riwayat obrolan <b>tak terbatas</b>",
    "<b>Unlimited</b> integrations": "Integrasi <b>tak terbatas</b>",
    "<b>Unlimited</b> public rooms": "Room publik <b>tak terbatas</b>",
    "<b>Unlimited</b> private rooms": "Room pribadi <b>tak terbatas</b>",
    "Limited to 25 users per private room": "Terbatas untuk 25 pengguna per room pribadi",
    "<b>Get started</b> for free": "<b>Memulai</b> secara gratis",
    "Premium Plans": "Rencana Premium",
    "starting from": "mulai dari",
    "per month": "per bulan",
    "Community <b>insights</b> & analytics": "Komunitas <b>insight</b> & analisis",
    "Community <b>engagement</b> & marketing tools": "Komunitas <b>engagement</b> & alat pemasaran",
    "<b>Customisable look</b> of the community rooms": "<b>Tampilan</b> komunitas yang dapat disesuaikan",
    "<b>PR & promotional</b> tools": "<b>PR & alat promosi</b>",
    "Access to <b>community managers</b>": "Akses ke <b>pengelola komunitas</b>",
    "<b>Join</b> earlybird programme": "<b>Bergabung</b> dengan program earlybird",

    "Get Gitter now!": "Dapatkan Gitter sekarang juga!",
    "Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter tersedia di semua browser modern serta aplikasi untuk komputer dan ponsel.",
    "We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "Saat ini kami memiliki aplikasi untuk OSX, iOS, Android, Windows dan Linux. Kami juga memiliki <a %s>jembatan IRC</a> yang manis",
    "Mac": "Mac",
    "Windows": "Windows",
    "Linux 32": "Linux 32",
    "Linux 64": "Linux 64",
    "iPhone": "iPhone",
    "Android": "Android"
}
