{
	"Integrations": "Integrazioni",
	"Pricing": "Prezzi",
	"Apps": "Applicazioni",
	"Existing user login": "Ho già un utente",
	"login": "login",
	"Chat, for GitHub.": "Chat, per GitHub.",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $5 per user per month. No credit card required.": "Stanze pubbliche e chat uno-a-uno illimitati, gratis per sempre. Offerte per gruppi privati a partire da $5 a utente/mese. Carta di credito non obbligatoria.",
	"Sign up free with Github": "Registrati gratuitamente con Github",
	"Sign up with Github": "Registrati con Github",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "Registrandoti accetti i nostri <a %s>Termini e Condizioni</a>",
	"Markdown power": "Potere del Markdown",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "Vuoi usare tutta la sintassi markdown in chat? E che ne dici della sintassi colorata?",
	"Yip, we got your back.": "Si, siamo con te",
	"Private conversations": "Conversazioni Private",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Le stanze pubbliche sono belle (e gratuite), ma sappiamo che certe cose sono private. Quindi abbiamo delle <a %s>offerte per questo</a>.",
	"Developer friendly": "Per Sviluppatori",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "Questa è l'immagine di una nuvola (cloud) su uno sfondo di nuvole. Mamma mia! Ci <a %s>Integriamo</a> con mucchio di roba nel cloud.",
	"Some of our communities": "Alcune delle nostre comunità",
	"Create your own": "Crea la tua",
	"Explore rooms": "Esplora le stanze",
	"Explore": "Esplora",
	"Integrated with your workflow": "Integrato con il tuo processo di lavoro",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter è basato su GitHub ed è fortemente integrato con le tue organizzazioni, repositories, issues e attività.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Forniamo integrazioni per Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. Integriamo anche webhooks personalizzati, con un <a %s>repository open source</a> per integrazioni così come con le <a %s>API</a>.",
	"Loved by our users": "Amato dai nostri utenti",
	"Gitter is nothing without the people using it day in and day out.": "Gitter non sarebbe nulla senza le persone che lo usano tutti i giorni.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Abbiamo chiesto a qualcuno cosa Gitter significhi per loro, questo è quello che hanno risposto. Se ti piace Gitter, Twittaci con <a %s>%s</a> e aggiorneremo le citazioni mensilmente.",
	"Personal pricing": "Prezzi utente",
	"Free": "Gratuito",
	"Forever": "Per sempre",
	"<b>Unlimited</b> public rooms": "Stanze pubbliche <b>illimitate</b>",
	"<b>1</b> private room": "<b>1</b> stanza privata",
	"<b>2 weeks’</b> chat history": "<b>2 settimane</b> di storico della chat",
	"<b>Get started</b> for free": "<b>Inizia</b> gratuitamente",
	"Individual": "Individuale",
	"monthly": "al mese",
	"<b>Unlimited</b> private rooms": "Stanze private <b>illimitate</b>",
	"<b>Unlimited</b> chat history": "Storico della chat <b>illimitato</b>",
	"<b>Purchase</b> now": "<b>Acquista</b> ora",
	"Organisation pricing": "Prezzi per le Organizzazioni",
	"Bronze": "Bronzo",
	"per user/month": "per utente al mese",
	"<b>6 months’</b> chat history": "<b>6 mesi</b> di storico delle chat",
	"Silver": "Argento",
	"Our free plan includes one private room per organisation you belong to on GitHub": "L'offerta gratuita include una stanza privata per ogni organizzazione di cui sei membro su GitHub",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "L'offerta individuale permette di creare stanze private utilizzando il proprio account come owner",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Le nostre offerte per le Organizzazioni ti permettono di creare stanze private utilizzando le organizzazioni di GitHub come owner",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "I prezzi possono essere soggetti a VAT. Registrandoti accetti i nostri <a %s>Termini e Condizioni</a>.",
	"Get Gitter now!": "Scarica Gitter adesso!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter è disponibile in tutti i browser moderni e anche con apps per desktops e cellulari.",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "Al momento abbiamo apps per OSX, iOS, Android, Windows and Linux. Abbiamo anche un carinissimo <a %s>IRC bridge</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "Da sviluppatori, per sviluppatori",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter è sviluppato a Londra da programmatori come te. Anche chi gestisce il prodotto scrive del codice, anche se quel poco che fa va sempre riscritto.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "Se vi trovate dalle parti di Silicon Roundabout, fate un salto da noi, amiamo incontrare altri sviluppatori.",
	"Support": "Supporto",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Dove gli sviluppatori chattano.",
	"Translated By": "-",
	"Pro": "Pro",
	"<b>25</b> org members": "<b>25</b> membri nell'organizzazione",
	"<b>Unlimited</b> org members": "Membri <b>illimitati</b> nelle organizzazioni",
	"<b>Unlimited</b> integrations": "Integrazioni <b>illimitate</b>",
	"Limited to 25 users per private room": "Limitato a 25 utenti per stanze private",
	"<b>Unlimited</b> users per private room": "Utenti <b>illimitati</b> per stanze private"
}
