{
	"Integrations": "ワークフローの統合について",
	"Pricing": "価格設定",
	"Apps": "アプリ",
	"Existing user login": "既存のユーザーはこちらからログイン",
	"login": "ログイン",
	"Chat, for GitHub.": "開発者が話をする場所",
	"Sign up free with Github": "GitHubで無料登録",
	"Sign up with Github": "GitHubで登録",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "登録により<a %s>利用条件</a>に同意したものとみなします。",
	"Markdown power": "Markdownの力",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "今までチャットでMarkdownが使いたくなったことはありませんか？また、シンタックスハイライトについてはどうですか？",
	"Yip, we got your back.": "Gitterが助けになります。",
	"Private conversations": "プライベートな会話",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "パブリックルームは最高です（しかも無料）。しかし、プライベートなこともあります。ですから<a %s>プライベートプラン</a>もご用意しています。",
	"Developer friendly": "開発者にやさしい",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "これはクラウドの背景にあるクラウドの絵です。すごい！我々は数多くのものをクラウドに<a %s>統合</a>しています。",
	"Some of our communities": "いくつかのコミュニティ",
	"Create your own": "自分用を作成する",
	"Explore rooms": "チャットルームを検索する",
	"Explore": "検索する",
	"Integrated with your workflow": "ワークフローを統合",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "GitterはGitHub上に構築され組織、レポジトリ、課題、アクティビティと緊密に統合されています。",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "当社はTrello、Jenkins、Travis CI、Heroku、Sentry、BitBucket、HuBoard、Logentries、PagerdutyおよびSprintlyとの統合を提供しています。また、カスタムの<a %s>Webhooks</a>にも対応し、フレキシブルな<a %s>API</a>だけでなくワークフローの統合のためのオープンソースリポジトリも保有しています。",
	"Loved by our users": "ユーザーから愛されています。",
	"Gitter is nothing without the people using it day in and day out.": "Gitterは毎日利用してくださる方無しには存在し得ません。",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "ユーザーたちがギッターが何を意味するかとの質問に答えてくれました。ギッターが好きなら@gitchatにツィートしてください。毎月その引用を更新しています。",
	"Personal pricing": "個人の価格",
	"Free": "無料",
	"Forever": "永久",
	"<b>Unlimited</b> public rooms": "<b>無制限の</b>パブリックチャットルーム",
	"<b>1</b> private room": "<b>1</b>個のプライベートチャットルーム",
	"<b>2 weeks’</b> chat history": "<b>2週間</b>のチャット履歴",
	"<b>Get started</b> for free": "無料で始める",
	"Individual": "個人",
	"monthly": "月額",
	"<b>Unlimited</b> private rooms": "<b>無制限の</b>プライベートチャットルーム",
	"<b>Unlimited</b> chat history": "<b>無制限の</b>チャット履歴",
	"<b>Purchase</b> now": "今すぐ購入",
	"Organisation pricing": "法人価格",
	"Bronze": "ブロンズ",
	"per user/month": "ユーザー/月毎",
	"<b>6 months’</b> chat history": "<b>半年間</b>のチャット履歴",
	"Silver": "シルバー",
	"Our free plan includes one private room per organisation you belong to on GitHub": "無料プランにはユーザーがGitHub上で所属している組織ごとに1つのプライベートルームが含まれています。",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "個人プランではあなたの個人アカウントをオーナーとして利用するプライベートルームを作成することができます。",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "法人プランではGitHubの組織をオーナーとして利用するプライベートルームを作成することができます。",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "価格は税別です。登録により<a %s>利用条件</a>に同意したものとみなします。",
	"Get Gitter now!": "今すぐGitterを始めよう！",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitterはデスクトップや携帯電話向けのアプリだけでなくすべての最新ブラウザでご利用いただけます。",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "現在、OSX、iOS、Android、Linux、Windowsのアプリがご利用いただけます。非常に小さな<a %s>IRC bridge</a>も有ります。",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "開発者から開発者へ",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitterはあなたのような開発者によりロンドンで設立されました。製作者であってもコードを書きます。それらは大概、後から書き直すことになりますが。",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "東ロンドンにお越しの際はぜひご連絡ください。私たちは開発者に会って話すことが大好きです。",
	"Support": "サポート",
	"API": "API",
	"Blog": "ブログ",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; 開発者が話をする場所",
	"Translated By": "-",
	"<b>Unlimited</b> integrations": "<b>無制限の</b>インテグレーション",
	"Limited to 25 users per private room": "各プライベートチャットルームにつき最大ユーザー25人まで。",
	"Pro": "プロ",
	"<b>Unlimited</b> users per private room": "プライベートチャットルームのユーザー人<b>数無制限</b>",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $5 per user per month. No credit card required.": "無制限のパブリックルームと一対一のチャットが永久に無料。<br />プライベートチームプランも毎月＄５から。<br />クレジットカードも不要です。"
}
