{
	"Integrations": "インテグレーション",
	"Pricing": "価格設定",
	"Apps": "アプリ",
	"Existing user login": "既存のユーザーログイン",
	"login": "ログイン",
	"Chat, for GitHub.": "開発者が話をする場所",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "私たちは世界中の開発者が集まりプログラミングの未来や、より良い製品の構築、ネコのGIFなどについて話し合うパブリックなコミュニティを数多く主催しています。",
	"Sign up free with Github": "GitHubで登録",
	"Sign up with Github": "GitHubで登録",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "<a %s>登録することにより当社利用条件に同意したものとみなします。</a>",
	"Markdown power": "Markdownのパワー",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "今までチャットでMarkdownが使いたくなったことはありませんか？　シンタックスハイライトはどうですか？　",
	"Yip, we got your back.": "Gitterが助けになります。",
	"Private conversations": "プライベートな会話",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "パブリックリームは最高です（しかも無料）、しかしプライベートなものもあります。ですからそれ向けのプランもご用意しています。",
	"Developer friendly": "開発者にやさしい",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "これはクラウドの背景に対するクラウドの絵です。うわあ！　我々は数多くのものクラウドに統合しています。",
	"Some of our communities": "いくつかのコミュニティ",
	"Create your own": "自分用を作成する",
	"Explore rooms": "探る",
	"Explore": "探る",
	"Integrated with your workflow": "ワークフローと統合",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "GitterはGitHub上に構築され組織、レポジトリ、問題、アクティビティと緊密に統合されています。",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "当社はTrello、Jenkins、Travis CI、Heroku、Sentry、BitBucket、HuBoard、Logentries、PagerdutyおよびSprintlyとの統合を実現します。またカスタムの<a %s>Webhooks</a>にも対応し、フレキシブルな<a %s>API</a>だけでなく統合向けのオープンソースレポジトリも保有しています。",
	"Loved by our users": "当社のユーザーから愛されている",
	"Gitter is nothing without the people using it day in and day out.": "Gitterは毎日それを利用する人なしに存在しえません。",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "当社はGitterが彼らにとって何を意味するか、彼らに話を尋ねることはあまりありません。Gitterが好きであれば是非<a %s>%s</a> へツイートしてください。当社はこれらを引用し毎月更新しています。",
	"Personal pricing": "個人価格",
	"Free": "無料",
	"Forever": "永久",
	"<b>Unlimited</b> public rooms": "<b>無制限の</b>パブリックルーム",
	"<b>1</b> private room": "<b>1</b>個のプライベートルーム",
	"<b>2 weeks’</b> chat history": "<b>2週間</b>のチャット履歴",
	"<b>Get started</b> for free": "無料で始める",
	"Individual": "個人",
	"monthly": "個人",
	"<b>Unlimited</b> private rooms": "<b>無制限の</b>パブリックルーム",
	"<b>Unlimited</b> chat history": "<b>無制限の</b>プライベートルーム",
	"<b>Purchase</b> now": "今すぐ購入",
	"Organisation pricing": "法人価格",
	"Bronze": "ブロンズ",
	"per user/month": "ユーザー/月毎",
	"<b>6 months’</b> chat history": "<b>半年間</b>のチャット履歴",
	"Silver": "シルバー",
	"Our free plan includes one private room per organisation you belong to on GitHub": "当社の無料プランにはユーザーがGitHub上で所属している法人ごとに1つのプライベートルームが含まれています。",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "当社の個人プランでは個人のアカウントをオーナーとして利用するプライベートルームを作成することができます。",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "当社の法人プランにはGitHubの組織をオーナーとして利用するプライベートルームを作成することができます。",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "<a %s>登録することにより当社利用条件に同意したものとみなします。</a>.",
	"Get Gitter now!": "今すぐGitterを入手しよう！",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitterはデスクトップや携帯電話向けのアプリだけでなくすべての最新ブラウザでご利用いただけます。",
	"We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>": "当社には現在、OSX、iOS、Chrome向けのアプリがあり、Android、Linux、Windowsで動作します。非常に小さな <a %s>IRC bridge</a>もあります。",
	"Mac": "Mac",
	"Windows": "Windows",
	"Coming soon": "近日公開",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "開発者から開発者へ",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitterはちょうどあなたのような開発者が集うチームによってロンドンに設立されました。 プロダクトガイであってもコードを書きます。それらは大概、最後にリライトが必要になりますが。",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "シリコンラウンドアバウトにいたことのある方はぜひご連絡ください。他の開発者もまじえてミーティングを行いましょう。",
	"Support": "サポート",
	"API": "API",
	"Blog": "ブログ",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; 開発者が話をする場所",
	"Translated By": ""
}
