{
	"Translated By": "-",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Where developers come to talk.",
	"Integrations": "Integrations",
	"Pricing": "가격정책",
	"Apps": "앱스",
	"Sign In to Start Talking": "기터 가입하기",
	"login": "로그인",
	"API": "API",
	"Blog": "블로그",
	"Twitter": "트위터",
	"Support": "고객지원",

	"Where communities thrive": "Where communities thrive",
	"Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter는 메시징, 컨텐트 및 검색을 통해 커뮤니티를 관리, 성장 및 연결하는 데 도움이되는 채팅 및 네트워킹 플랫폼입니다.",
	"Create your own community": "자신만의 커뮤니티 만들기",
	"Explore other communities": "다른 커뮤니티 탐색",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "가입하면 <a href="#">이용 약관</a>에 동의하게됩니다.",
	"Free without limits": "무제한 무료",
	"Enjoy free public communities with unlimited people, message history and integrations.": "제한 없는 메시지 기록 및 통합을 통해 무료 공개 커뮤니티를 즐기십시오.",
	"Simple to create": "간단한 시작",
	"Simply create your community and start talking - no need to set up any invitation services.": "커뮤니티를 만들고 말하기 만하면 초대 서비스를 설정할 필요가 없습니다.",
	"Quick to grow": "빠른 성장",
	"Grow your community in no time with our easy sharing tools.": "쉬운 공유 도구로 커뮤니티를 빠르게 성장하십시오.",
	"Out in the open": "외부 공개",
	"Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "커뮤니티를 쉽게 찾을 수 있게 하세요! Gitter를 사용하면 모든 사람들이 디렉토리 및 검색 엔진을 통해 커뮤니티를 발견할 수 있습니다.",

	"Trusted by": "우리의 고객들",
	"Some of our communities": "우리 서비스내의 커뮤니티들",
	"Create your own": "Create your own",
	"Explore rooms": "Explore rooms",
	"Explore": "Explore",
	"GitterHQ": "GitterHQ",
	"Let’s talk about Gitter!": "Let’s talk about Gitter!",

	"Designed for community collaboration": "Designed for community collaboration",
	"Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.",
	"We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.",

	"Loved by our users": "Loved by our users",
	"Gitter is nothing without the people using it day in and day out.": "Gitter is nothing without the people using it day in and day out.",
	"We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.",

	"Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.",
	"Free": "Free",
	"Forever": "Forever",
	"<b>Unlimited</b> chat history": "<b>Unlimited</b> chat history",
	"<b>Unlimited</b> integrations": "<b>Unlimited</b> integrations",
	"<b>Unlimited</b> public rooms": "<b>Unlimited</b> public rooms",
	"<b>Unlimited</b> private rooms": "<b>Unlimited</b> private rooms",
	"Limited to 25 users per private room": "Limited to 25 users per private room",
	"<b>Get started</b> for free": "<b>Get started</b> for free",
	"Premium Plans": "Premium Plans",
	"starting from": "starting from",
	"per month": "per month",
	"Community <b>insights</b> & analytics": "Community <b>insights</b> & analytics",
	"Community <b>engagement</b> & marketing tools": "Community <b>engagement</b> & marketing tools",
	"<b>Customisable look</b> of the community rooms": "<b>Customisable look</b> of the community rooms",
	"<b>PR & promotional</b> tools": "<b>PR & promotional</b> tools",
	"Access to <b>community managers</b>": "Access to <b>community managers</b>",
	"<b>Join</b> earlybird programme": "<b>Join</b> earlybird programme",

	"Get Gitter now!": "Get Gitter now!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter is available in all modern browsers as well as apps for desktops and mobile phones.",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android"
}
