{
	"Translated By": "-",
	"Gitter &mdash; Where developers come to talk.": "Gitter & mdash; 개발자들이 모이는 곳",
	"Integrations": "서비스 통합",
	"Pricing": "가격정책",
	"Apps": "앱스",
	"Sign In to Start Talking": "Gitter 가입하기",
	"login": "로그인",
	"API": "API",
	"Blog": "블로그",
	"Twitter": "트위터",
	"Support": "고객지원",

	"Where communities thrive": "커뮤니티들의 공간",
	"Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter는 메시징, 컨텐트 및 검색을 통해 커뮤니티를 관리, 성장 및 연결하는 데 도움이되는 채팅 및 네트워킹 플랫폼입니다.",
	"Create your own community": "자신만의 커뮤니티 만들기",
	"Explore other communities": "다른 커뮤니티 탐색",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "가입하면 <a href="#">이용 약관</a>에 동의하게됩니다.",
	"Free without limits": "무제한 무료",
	"Enjoy free public communities with Unlimited people, message history and integrations.": "제한 없는 메시지 기록 및 통합을 통해 무료 공개 커뮤니티를 즐기십시오.",
	"Simple to create": "간단한 시작",
	"Simply create your community and start talking - no need to set up any invitation services.": "커뮤니티를 만들고 말하기 만하면 초대 서비스를 설정할 필요가 없습니다.",
	"Quick to grow": "빠른 성장",
	"Grow your community in no time with our easy sharing tools.": "쉬운 공유 도구로 커뮤니티를 빠르게 성장하십시오.",
	"Out in the open": "외부 공개",
	"Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "커뮤니티를 쉽게 찾을 수 있게 하세요! Gitter를 사용하면 모든 사람들이 디렉토리 및 검색 엔진을 통해 커뮤니티를 발견할 수 있습니다.",

	"Trusted by": "우리의 고객들",
	"Some of our communities": "우리 서비스내의 커뮤니티들",
	"Create your own": "Gitter를 만들어 보세요",
	"Explore rooms": "다른 방들을 찾아보기",
	"Explore": "찾아보기",
	"GitterHQ": "GitterHQ",
	"Let’s talk about Gitter!": "Gitter에 대해 이해기해보세요!",

	"Designed for community collaboration": "커뮤니티 협업을 위해 설계되었습니다",
	"Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "Gitter는 커뮤니티 메시징, 공동 작업 및 검색을 가능한 한 원활하고 간단하게 만들 수 있도록 설계되었습니다. 커뮤니티를 손쉽게 만들고 조직하고 성장시켜 다른 사람들을 클릭 한 번으로 참여시킬 수 있습니다.",
	"We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "우리는 GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly와의 통합도 제공합니다. 우리는 맞춤 웹 훅을 허용하고, 통합을 위한 <a %s>오픈 소스 저장소</a> 및 <a %s>유연한 API</a>를 보유하고 있습니다.",

	"Loved by our users": "우리의 사용자들에게 사랑받기",
	"Gitter is nothing without the people using it day in and day out.": "사람들이 매일매일 사용하지 않으면 Gitter는 의미가 없습니다.",
	"We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "우리는 Gitter가 그들에게 무엇을 의미하는지 사람들에게 물었습니다. Gitter를 좋아한다면, 우리에게 <a %s> % s </a>을 의뢰하십시오. 우리는 매달 이 인용문을 업데이트 할 것입니다..",

	"Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "가격 책정 계획은 2017 년 초에 시작됩니다. Earlybird 프로그램에 지금 가입하고 75% 할인을 받으십시오.",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "가격에는 VAT가 부과 될 수 있습니다. 가입하시면 <a %s>이용 약관</a>에 동의하게 됩니다.",
	"Free": "무료",
	"Forever": "평생",
	"<b>Unlimited</b> chat history": "<b>무제한</b> 채팅 기록",
	"<b>Unlimited</b> integrations": "<b>무제한</b> 서비스 통합",
	"<b>Unlimited</b> public rooms": "<b>무제한</b> 공개방",
	"<b>Unlimited</b> private rooms": "<b>무제한</b> 비공개방",
	"Limited to 25 users per private room": "비공개방당 최대 25명 가능",
	"<b>Get started</b> for free": "무료로 <b>시작하세요</b>",
	"Premium Plans": "프리미엄 서비스",
	"starting from": "시작하세요",
	"per month": "매달",
	"Community <b>insights</b> & analytics": "Community <b>insights</b> & analytics",
	"Community <b>engagement</b> & marketing tools": "Community <b>engagement</b> & marketing tools",
	"<b>Customisable look</b> of the community rooms": "<b>Customisable look</b> of the community rooms",
	"<b>PR & promotional</b> tools": "<b>PR & promotional</b> tools",
	"Access to <b>community managers</b>": "Access to <b>community managers</b>",
	"<b>Join</b> earlybird programme": "Earlybird 프로그램에 <b>참여하기<b>",

	"Get Gitter now!": "지금 Gitter를 시작하세요!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter는 모든 최신 브라우저와 데스크톱 및 스마트폰 앱에서 사용할 수 있습니다.",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "현재 OSX, iOS, Android, Windows 및 Linux 용 앱을 보유하고 있습니다. 우리는 또한 <a %s>IRC 브릿지</a>를 가지고 있습니다.",
	"Mac": "맥",
	"Windows": "윈도우즈",
	"Linux 32": "리눅스 32",
	"Linux 64": "리눅스 64",
	"iPhone": "아이폰",
	"Android": "안드로이드"
}
