{
	"Integrations": "Integrações",
	"Pricing": "Preços",
	"Apps": "Aplicativos",
	"Existing user login": "Efetuar Login",
	"login": "login",
	"Chat, for GitHub.": "Chat, para GitHub.",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "Obtenha salas de conversas públicas ou uma conversa em particular, grátis! Há planos para grupos privados começando a partir de $2 por usuário/mês. Não precisa informar seu cartão de crédito no cadastro.",
	"Sign up free with Github": "Entre agora com sua conta GitHub, grátis!",
	"Sign up with Github": "Entre com GitHub",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "Ao cadastrar-se agora você concorda com os nossos <a %s>Termos e Condições de Uso</a>",
	"Markdown power": "Markdown power",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "Já quis suporte ao Markdown no chat? E o que acha de usar 'syntax highlighting'?",
	"Yip, we got your back.": "Ufa! Você voltou!",
	"Private conversations": "Conversas privadas",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Salas Públicas são incríveis (e grátis), mas as vezes queremos algumas coisas privadas. Então, nós temos <a %s>planos para isso</a>.",
	"Developer friendly": "Developer friendly",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "Essa é uma figura de uma nuvem contra um fundo de nuvens. WOW! <a %s>Integramos</a> com um monte de coisas na nuvem.",
	"Some of our communities": "Algumas de nossas comunidades",
	"Create your own": "Crie a sua própria",
	"Explore rooms": "Explore salas",
	"Explore": "Explore",
	"Integrated with your workflow": "Integrado com seu jeito de trabalhar",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter é feito sobre o GitHub e fortemente integrado com suas organizações, repositórios, issues e atividades.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Provemos integrações com Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. Também integramos com Webhooks personalizados e temos um <a %s>repositório de Código Aberto</a> para integrações, bem como uma <a %s>API muito flexível</a>.",
	"Loved by our users": "Amado por nossos úsuários",
	"Gitter is nothing without the people using it day in and day out.": "Gitter não é nada se não fosse pelas pessoas usando-o no dia-a-dia à fora.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Perguntamos para alguns usuários o que o Gitter significa para eles, e isso é o que eles disseram. Se você também ama o Gitter, tweet para <a %s>%s</a> e nós atualizaremos essas frases todo mês.",
	"Personal pricing": "Preço por pessoa",
	"Free": "Grátis",
	"Forever": "Para sempre",
	"<b>Unlimited</b> public rooms": "Salas públicas <b>ilimitadas</b>",
	"<b>1</b> private room": "<b>1</b> sala privada",
	"<b>2 weeks’</b> chat history": "Histórico de <b>2 semanas</b>",
	"<b>Get started</b> for free": "<b>Comece grátis</b>",
	"Individual": "Individual",
	"monthly": "mensal",
	"<b>Unlimited</b> private rooms": "Salas privadas <b>ilimitadas</b>",
	"<b>Unlimited</b> chat history": "Histórico <b>ilimitado</b>",
	"<b>Purchase</b> now": "<b>Compre</b> agora",
	"Organisation pricing": "Preço para Empresas",
	"Bronze": "Bronze",
	"per user/month": "por usuário/mês",
	"<b>6 months’</b> chat history": "<b>6 meses</b> histórico",
	"Silver": "Prata",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Nosso plano gratuito inclui uma sala privada por organização que você pertença no Github",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Nosso plano Individual permite que você crie salas privadas usando sua conta pessoal como 'dono da sala'",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Nossos planos Empresariais permitem que você crie salas privadas usando sua Organização do GitHub como 'dona da sala'",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Preços estão sujeitos a taxas (impostos), de acordo com a legislação de seu País. Ao cadastrar-se, você concorda com os nossos <a %s>Termos e Condições de Uso</a>.",
	"Get Gitter now!": "Obtenha o Gitter agora!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter está disponível em todos os navegadores modernos, bem como em aplicativos Desktop e para celulares/tablets.",
	"We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>": "Atualmente temos aplicativos para OSX, iOS, Android e Windows. Uma versão para Linux chegará em breve. Também temos uma pequena 'ponte' para <a %s>canais IRC</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Coming soon": "Em breve",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "Por desenvolvedores, para desenvolvedores",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter é feito em Londres por um time de desenvolvedores, como você. E cara, mesmo o responsável pelo produto escreve código, embora geralmente nós acabamos re-escrevendo esses bits.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "Se você estiver na área de Silicon Roundabout, vem dar um 'Alô' pra gente, adoramos conhecer outros desenvolvedores.",
	"Support": "Suporte",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Onde desenvolvedores vêm conversar.",
	"Translated By": "<a href='https://github.com/mariojunior' title='Mario Junior no Github' target='_blank'>Mario Junior</a> e <a href='https://github.com/ianramosc' title='Ian Ramos no Github' target='_blank'>Ian Ramos</a>"
}
