{
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Где общаются разработчики",
	"Integrations": "Интеграция",
	"Pricing": "Тарифы",
	"Apps": "Приложения",
	"Existing user login": "существующие пользователи",
	"login": "существующие пользователи",
	"Chat, for GitHub.": "Где общаются разработчики",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $5 per user per month. No credit card required.": "У нас размещаются тысячи публичных сообществ, в которых разработчики со всего мира собираются, чтобы обговорить будущее программирования, создавать лучшие продукты и поделиться лучшими картинками котов.",
	"Sign up free with Github": "Зарегистрируйтесь с GitHub",
	"Sign up with Github": "Зарегистрируйтесь с GitHub",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "<a %s>Регистрируясь, вы соглашаетесь с условиями пользовательского соглашения.</a>",
	"Markdown power": "Markdown",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "Мечтали о полной поддержке markdown в чате? А как на счет подсветки синтаксиса?",
	"Yip, we got your back.": "Их есть у нас!",
	"Private conversations": "Конфиденциальные",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Открытые комнаты прекрасны (и бесплатны), но некоторые вещи являются конфиденциальными. <a %s>У нас есть решение и для этого</a>.",
	"Developer friendly": "Интегрированный",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "Это картинка облака на фоне облаков. Вы угадали! <a %s>Мы интегрируемся</a> с множеством облачных продуктов.",
	"Some of our communities": "Некоторые из наших сообществ",
	"Create your own": "Создай собственное",
	"Explore rooms": "исследовать",
	"Explore": "исследовать",
	"Integrated with your workflow": "Интеграция с вашим рабочим процессом",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter создан на базе GitHub и хорошо интегрирован с вашими организациями, хранилищами, проблемами и деятельностью.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Мы обеспечили интеграцию с Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty и Sprintly. Мы также принимаем пользовательские <a %s>webhook-и</a> и имеем хранилища с открытым исходным кодом для интеграции наравне с гибким <a %s>API</a>.",
	"Loved by our users": "Любимый нашими пользователями",
	"Gitter is nothing without the people using it day in and day out.": "Без людей, которые пользуются им день ото дня, Gitter является ничем.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Мы спросили некоторых пользователей, что для них означает Gitter и вот что они должны были сказать. Если вам нравится Gitter, пишите об этом в Twitter пользователю <a %s>%s</a>, и мы будем обновлять эти сообщения каждый месяц.",
	"Personal pricing": "Отдельные пользователи",
	"Free": "Бесплатный",
	"Forever": "Навсегда",
	"<b>Unlimited</b> public rooms": "<b>Неограниченные</b> общие комнаты",
	"<b>1</b> private room": "<b>1</b> частная комната",
	"<b>2 weeks’</b> chat history": "История чата за <b>2 недели</b>",
	"<b>Get started</b> for free": "<b>Стартуйте бесплатно</b>",
	"Individual": "Индивидуальный",
	"monthly": "Месячный",
	"<b>Unlimited</b> private rooms": "<b>Неограниченные</b> общие комнаты",
	"<b>Unlimited</b> chat history": "<b>Неограниченные</b> частные комнаты",
	"<b>Purchase</b> now": "<b>Купите</b> сейчас",
	"Organisation pricing": "Организации",
	"Bronze": "Бронза",
	"per user/month": "За пользователя в месяц",
	"<b>6 months’</b> chat history": "История чата за <b>6 месяцев</b>",
	"Silver": "Серебро",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Наш бесплатный план включает одну приватную комнату в GitHub для организации, к которой вы относитесь",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Наш индивидуальный план позволяет вам создавать приватные комнаты в качестве владельца, используя свою личную учетную запись",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Наши планы для организаций позволяют вам создавать приватные комнаты, используя в качестве владельца GitHub",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "<a %s>Регистрируясь, вы соглашаетесь с условиями пользовательского соглашения.</a>",
	"Get Gitter now!": "Присоединяйтесь к Gitter сейчас!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter доступен для всех современных браузеров, а также в виде мобильных приложений и приложений для рабочего стола.",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "У нас есть приложения для OSX, iOS, Android, Linux и Windows. Также у нас есть милый <a %s>IRC</a> мост.",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "От разработчиков разработчикам",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter создан в Лондоне командой таких же разработчиков, как вы. Чего таить (елы-палы), даже менеджер писал код, хотя мы обычно переписывали созданные им части.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "Если вы когда-либо будете пробегать мимо Silicon Roundabout, кричите нам, мы любим встречаться с другими разработчиками.",
	"Support": "Поддержка",
	"API": "API",
	"Blog": "Блог",
	"Twitter": "Twitter",
	"Translated By": "-"
}
