{
	"Integrations": "Integrácia",
	"Pricing": "Ceny",
	"Apps": "Aplikácie",
	"Existing user login": "Existující užívateľský účet",
	"login": "prihlásenie",
	"Chat, for GitHub.": "Chat, pre GitHub.",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "Získajte neobmedzené verejné miestnosti a one-to-one chaty, navždy zdarma. Súkromé týmové plány začínajú od $2 za užívateľa mesačne. Kreditná karta nie je  vyžadovaná.",
	"Sign up free with Github": "Zaregistrujte sa zdarma s GitHubem",
	"Sign up with Github": "Zaregistrujte sa s GitHubem",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "Registráciou súhlasíte s našimi <a %s>Všeobecnými zmluvnými podmienkami</a>",
	"Markdown power": "Sila Markdownu",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "Chceli ste niekedy plnú podporu markdown v chate? A co zvýrazňovanie syntaxu?",
	"Yip, we got your back.": "Áno, máme to.",
	"Private conversations": "Súkromé konverzácie",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Verejné miestnosti sú super (a zdarma), ale vieme, že niektoré veci sú súkromé. Takže máme <a %s>plány pre toto</a>.",
	"Developer friendly": "Priateľské pre vývojárov",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "Toto je obrázok mraku na pozadí mrakov. OMG! <a %s>Začleňujeme</a> hromadu vecí v kloude.",
	"Some of our communities": "Niektoré z našich komunít",
	"Create your own": "Vytvor svoju vlastnú",
	"Explore rooms": "Prezkúmej miestnosti",
	"Explore": "Prozkúmať",
	"Integrated with your workflow": "Integruj so svojim pracovním postupom",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter je postavený na vrchole GitHubu a je úzko spojený s Vašimi organizáciami, repozitármi, problémami a aktivitou.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Ponúkame integráciu s Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. Taktiež príjmame vlastné webhooks, máme <a %s>open source repozitár</a> pre integráciu tak ako <a %s>flexibilnú API</a>.",
	"Loved by our users": "Milované našimi užívateľmi",
	"Gitter is nothing without the people using it day in and day out.": "Gitter je nič bez ľudí používajúcich ho deň čo deň.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Opýtali sme sa skupiny ľudí, čo pro ně Gitter znamená, to je to čo museli říct. Pokiaľ milujete Gitter, Tweetnite nás <a %s>%s</a> a my budeme vylepšovať tieto citácie každý mesiac.",
	"Personal pricing": "Ceny pre jednotlivcov",
	"Free": "Zdarma",
	"Forever": "Navždy",
	"<b>Unlimited</b> public rooms": "<b>Neobmedzené</b> verejné miestnosti",
	"<b>1</b> private room": "<b>1</b> súkromná miestnosť",
	"<b>2 weeks’</b> chat history": "<b>2 týdny’</b> história chatu",
	"<b>Get started</b> for free": "<b>Začnite</b> zdarma",
	"Individual": "Individuálný",
	"monthly": "mesačne",
	"<b>Unlimited</b> private rooms": "<b>Neobmedzené</b> privatná miestnosti",
	"<b>Unlimited</b> chat history": "<b>Neobmedzená</b> história chatu",
	"<b>Purchase</b> now": "<b>Kúp</b> dnes",
	"Organisation pricing": "Ceny pre organizáce",
	"Bronze": "Bronz",
	"per user/month": "za užívateľa/mesiac",
	"<b>6 months’</b> chat history": "<b>6 mesiacov’</b> história chatu",
	"Silver": "Striebro",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Náš plán zdarma zahrňuje jednu privátnu miestnosť na organizáciu ku ktorej patríte na GitHub",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Náš individuálný plán dovoluje vytvárať súkromné miestnosti využitím Vášho súkromého účtu ako vlastník",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Náš plán pre organizácie dovoľuje vytvárať súkromné miestnosti s využitím Vášho GitHub účtu organizácie ako vlastník",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Ceny môžu byť predmetom DPH. Registráciou súhlasíte s <a %s>Všeobecnými zmluvnými podmienkami</a>.",
	"Get Gitter now!": "Získaj Gitter teraz!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter je dostupný vo všetkých moderních prehliadačoch tak ako v aplikácii pre stolné počítače a mobilné telefóny.",
	"We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>": "Aktuálne máme aplikáciu pre OSX, iOS, Android a Windows a aplikáciu pro Linux príde čoskoro. Taktiež máme sladký malý <a %s>IRC most</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Coming soon": "Už čoskoro",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "Od vývojárov, pre vývojárov",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter je založenýn v Londýne tímom vývojárov podobných ako vy. Sakra i ten chlapík od produktov píše kódy, avšak obvykle skončíme prepisováním tíchto kúskov.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "Pokiaľ niekedy budete v okolí Silicon Roundabout, dajte nám vedieť, máme radi stretávanie s ostatnými vývojármi.",
	"Support": "Podpora",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Kam sa developeri chodia rozprávať.",
	"Translated By": "Matus Mihok"
}
