{
	"Integrations": "Integrationer",
	"Pricing": "Prisplaner",
	"Apps": "Appar",
	"Existing user login": "Inloggning existerande användare" ,
	"login": "inloggning",
	"Chat, for GitHub.": "Chat, för GitHub.",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "få oändligt med öppna rum och en-och-en rum, gratis för alltid. Privata team prisplaner startar på $2 per användare per månad. Inget kreditkort behövs.",
	"Sign up free with Github": "Registrera dig gratis med GitHub",
	"Sign up with Github": "Registrera dig med github",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "genom att registrera dig godkänner du våra <a %s>Villkor</a>",
	"Markdown power": "Markdown power",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "någonsin önskar full markdown i chattar? Vad sägs som syntax highlighting?",
	"Yip, we got your back.": "Jup, Det har vi.",
	"Private conversations": "Privata konversationer",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Publika rum är super (och gratis), men vi fattar att vissa saker är privata. Så vi har <a %s>prisplaner för det/a>.",
	"Developer friendly": "Utvecklarvänligt",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "detta är en bild av ett moln, mot en bakgrund av moln. OMG! Vi <a %s>Integrerar</a> med en del grejer i molnet.",
	"Some of our communities": "Några av våra grupper",
	"Create your own": "Skapa din egen",
	"Explore rooms": "Utforska rum",
	"Explore": "Utforska",
	"Integrated with your workflow": "Integrerad med ditt arbetsflöde",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter är byggt på GitHub och är nära integrerat med dina organisationer, repositories, issues och aktivitet.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Vi har integreringar för Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. Vi accepterar även egna webhooks, har en <a %s>open source repository</a> för integrationer samt en <a %s>flexibel API</a>.",
	"Loved by our users": "Älskat av våra användare",
	"Gitter is nothing without the people using it day in and day out.": "Gitter är ingenting utan våra användare som använder det dag ut och dag in.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Vi frågade några vad gitter betyder för dem, detta är deras svar. Om du älskar Gitter, Tweeta oss <a %s>%s</a> så uppdaterar vi dessa citat var månad.",
	"Personal pricing": "Personlig prissättning",
	"Free": "Gratis",
	"Forever": "För alltid",
	"<b>Unlimited</b> public rooms": "<b>Oändligt</b> med publika rum",
	"<b>1</b> private room": "<b>1</b> privat rum",
	"<b>2 weeks’</b> chat history": "<b>2 veckors</b> chat historik",
	"<b>Get started</b> for free": "<b>Kom igång</b> Gratis",
	"Individual": "Individuellt",
	"monthly": "Månatlig",
	"<b>Unlimited</b> private rooms": "<b>Oändligt</b> med privata rum",
	"<b>Unlimited</b> chat history": "<b>Oändlig</b> chat historik",
	"<b>Purchase</b> now": "<b>Köp</b> nu",
	"Organisation pricing": "organisationsprisplaner",
	"Bronze": "Brons",
	"per user/month": "per användare per månad",
	"<b>6 months’</b> chat history": "<b>6 månader’</b> chat historik",
	"Silver": "Silver",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Var gartisplan erbjuder ett privat rum per organisation du tillhör på GitHub",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Our Individual plan allows you to create private rooms using your personal account as the owner",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Our organisation plans allow you to create private rooms using your GitHub organisation as the owner",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.",
	"Get Gitter now!": "Get Gitter now!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter is available in all modern browsers as well as apps for desktops and mobile phones.",
	"We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>": "We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Coming soon": "Coming soon",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "By developers, for developers",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.",
	"Support": "Support",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Where developers come to talk.",
	"Translated By": "Översatt Av"
}
