{
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Dit utvecklare kommer för att snacka.",
	"Integrations": "Integrationer",
	"Pricing": "Prisplaner",
	"Apps": "Appar",
	"Sign In to Start Talking": "Logga In för att Börja Skriva",
	"login": "inloggning",
	"API": "API",
	"Blog": "Blogg",
	"Twitter": "Twitter",
	"Support": "Support",

	"Where communities thrive": "Där gemenskaper frodas",
	"Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter är en chatt- och nätverksplattform som hjälper till med hantering, växande och koppla gemenskaper tillsammans genom meddelanden, innehåll och upptäckter.",
	"Create your own community": "Skapa din egna grupp",
	"Explore other communities": "Utforska andra grupper",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "Genom att registrera dig godkänner du våra <a %s>Terms and Conditions</a>",
	"Free without limits": "Gratis utan gränser",
	"Enjoy free public communities with unlimited people, message history and integrations.": "Njuta av gratis offentliga grupper med obegränsat antal människor, meddelandehistorik och integrationer.",
	"Simple to create": "Enkelt att börja",
	"Simply create your community and start talking - no need to set up any invitation services.": "Helt enkelt skapa din egen grupp och börja prata - inga tjänster för inbjudningar krävs.",
	"Quick to grow": "Snabbväxande",
	"Grow your community in no time with our easy sharing tools.": "Väx din gemenskap på nolltid med våra lätta verktyg för delning.",
	"Out in the open": "Ute i det fria",
	"Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "Låt din gemenskap upptäckas! Med Gitter kan alla hitta din grupp och gemenskap i vårt register och via sökmotorer.",

	"Trusted by": "Pålitad av",
	"Some of our communities": "Några av våra grupper",
	"Create your own": "Skapa din egna",
	"Explore rooms": "Utforska rum",
	"Explore": "Utforska",
	"GitterHQ": "GitterHQ",
	"Let’s talk about Gitter!": "Låt oss prata om Gitter!",

	"Designed for community collaboration": "Designad för gemenskap kollaboration",
	"Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "Gitter är designat för att göra gemenskap meddelanden, samarbeten och upptäckter så smidigt och enkelt som möjligt. Du kan enkelt skapa, organisera och växa din grupp, bjuda in andra att ansluta med bara ett klick.",
	"We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "Vi erbjuder också integreringar med GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. Vi stödjer egna webhooks, har en <a %s>open source repository</a> för integrationer såväl som en <a %s>flexibel API</a>.",

	"Loved by our users": "Älskad av våra användare",
	"Gitter is nothing without the people using it day in and day out.": "Gitter är ingenting utan våra användare som använder det dag ut och dag in.",
	"We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "Vi frågade några personer vad Gitter betyder för dem, detta är deras svar. Om du älskar Gitter, Twittra oss på <a %s>%s</a> så uppdaterar vi dessa citat varje månad.",

	"Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "Prisplanerna kommer tidigt 2017. Gå med i Earlybird programmet nu och få 75%% rabatt.",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Priserna kan variera tack vare moms. Genom att registrera dig godkänner du våra <a %s>Terms and Conditions</a>.",
	"Free": "Gratis",
	"Forever": "För alltid",
	"<b>Unlimited</b> chat history": "<b>Oändlig</b> chatthistorik",
	"<b>Unlimited</b> integrations": "<b>Oändlig</b> integration",
	"<b>Unlimited</b> public rooms": "<b>Oändligt</b> med öppna rum",
	"<b>Unlimited</b> private rooms": "<b>Oändligt</b> med privata rum",
	"Limited to 25 users per private room": "Begränsad till 25 användare per privata rum",
	"<b>Get started</b> for free": "<b>Kom igång</b> gratis",
	"Premium Plans": "Premium Planer",
	"starting from": "börjar från",
	"per month": "per månad",
	"Community <b>insights</b> & analytics": "Gemenskap <b>insikter</b> & analytisk",
	"Community <b>engagement</b> & marketing tools": "Gemenskap <b>engagemang</b> & marknadsföringsverktyg",
	"<b>Customisable look</b> of the community rooms": "<b>Justerbart utseende</b> av grupprummen",
	"<b>PR & promotional</b> tools": "<b>PR & kampanj-</b> verktyg",
	"Access to <b>community managers</b>": "Tillgång till <b>gemenskap verktygen</b>",
	"<b>Join</b> earlybird programme": "<b>Gå med i</b> earlybird programmet",

	"Get Gitter now!": "Skaffa Gitter nu!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter är tillgängligt i alla moderna webbläsare såväl som appar för datorer och mobiltelefoner.",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "Vi har just nu appar för OSX, iOS, Android, Windows och Linux. Vi har också en mysig liten <a %s>IRC brygga</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android",

	"Translated By": "Mattias A (Nubbie on GitHub) & svbeon"
}


// Old strings that got removed/after the community update - Saved for easy access if needed
	//"Chat, for GitHub.": "Chatt, för GitHub.",
	//"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "Få oändligt med öppna rum och privata en-och-en rum, gratis för alltid. Privata prisplaner startar på $2 per användare varje månad. Inget kreditkort behövs.",
	//"Sign up free with Github": "Registrera dig gratis med GitHub",
	//"Sign up with Github": "Registrera dig med Github",
	//"Markdown power": "Textformatering makt",
	//"Ever wanted full markdown support in chat? How about syntax highlighting?": "Någonsin önskat full textformatering i chattar? Vad sägs som syntax markeringar?", 
	//"Yip, we got your back.": "Yepp, det har vi.", 
	//"Private conversations": "Privata konversationer",
	//"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Offentliga rum är häftiga (och gratis), men vi fattar att vissa saker är privata. Så vi har <a %s>prisplaner för det/a>.",
	//"Developer friendly": "Utvecklarvänligt",
	//"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "Detta är en bild på ett moln, mot en bakgrund av moln. OMG! Vi <a %s>Integrerar</a> med massor i molnet.",
	//"Integrated with your workflow": "Integrerad med ditt arbetsflöde",
	//"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter är byggt på GitHub och är nära integrerat med dina organisationer, repositories, issues och aktiviteter.",
	//"Personal pricing": "Personlig prissättning",
	//"<b>1</b> private room": "<b>1</b> privatrum",
	//"<b>2 weeks’</b> chat history": "<b>2 veckors</b> chatt historik",
	//"Individual": "Individuell",
	//"<b>Purchase</b> now": "<b>Köp</b> nu",
	//"Organisation pricing": "Organisationsplaner",
	//"Bronze": "Brons",
	//"<b>6 months’</b> chat history": "<b>6 månader’</b> chatt historik",
	//"Silver": "Silver",
	//"Our free plan includes one private room per organisation you belong to on GitHub": "Vår gratisplan erbjuder ett privatrum per organisation du tillhör på GitHub",
	//"Our Individual plan allows you to create private rooms using your personal account as the owner": "Vår Individuella plan tillåter dig att skapa privata rum genom att använda ditt personliga konto som ägare",
	//"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Vår Organisationsplan tillåter dig att skapa privata rum via din GitHub organisation som ägare",
	//"Coming soon": "Kommer snart",
	//"By developers, for developers": "Av utvecklare, för utvecklare",
	//"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter är skapad i London av ett lag med utvecklare precis som du. För tusan, till och med vår VD programmerar, även om vi brukar få skriva om alla de bitarna.",
	//"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "Om du någonsin är runt Silicon Roundabout, kom förbi, vi älskar att träffa andra utvecklare.",
