{
  "Translated By": "-",
  "Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Where developers come to talk.",
  "Integrations": "Entegrasyonlar",
  "Pricing": "Ücretlendirme",
  "Apps": "Uygulamalar",
  "Sign In to Start Talking": "Konuşmaya başlamak için kaydolun",
  "login": "giriş",
  "API": "API",
  "Blog": "Blog",
  "Twitter": "Twitter",
  "Support": "Destek",

  "Where communities thrive": "Topluluklar nerede gelişiyor?",
  "Gitter is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.": "Gitter mesajlaşma ve paylaşma yoluyla toplulukları yönetmeye, büyütmeye ve bağlamaya yarayan bir sohbet ve ağ platformudur.",
  "Create your own community": "Kendi topluluğunu oluştur",
  "Explore other communities": "Diğer topluluklara göz at",
  "By signing up you agree to our <a %s>Terms and Conditions</a>": "Giriş yaparak <a %s>şart ve koşullarımızı</a> kabul etmiş olursunuz.",
  "Free without limits": "Sınırsız ücretsiz",
  "Enjoy free public communities with unlimited people, message history and integrations.": "Sınırsız katılımcı, sohbet geçmişi ve entegrasyon ile herkese açık topluluğun keyfini çıkarın.",
  "Simple to create": "Kolay oluşturma",
  "Simply create your community and start talking - no need to set up any invitation services.": "Hiç bir davetiye hizmeti ayarlamadan kolayca topluluğunuzu oluşturun ve konuşmaya başlayın.",
  "Quick to grow": "Hızlı büyüme",
  "Grow your community in no time with our easy sharing tools.": "Topluluğunuzu basit paylaşım araçlarımız ile zaman harcamadan kolay bir şekilde büyütün.",
  "Out in the open": "Herkese açık",
  "Let your community be discovered! With Gitter, everyone can find your community in our directory and via search engines.": "Topluluğunuzun keşfedilmesine izin verin! Herkes topluluğunuzu Gitter dizinimizde ve ya arama motorları aracılığı ile bulabilir.",

  "Trusted by": "Aşağıdaki şirketler Gitter'e güveniyor",
  "Some of our communities": "Topluluklarımızdan bazıları",
  "Create your own": "Kendinizinkini oluşturun",
  "Explore rooms": "Odalara göz atın",
  "Explore": "Göz atın",
  "GitterHQ": "GitterHQ",
  "Let’s talk about Gitter!": "Hadi Gitter hakkında konuşalım!",

  "Designed for community collaboration": "Topluluk işbirliği için tasarlandı",
  "Gitter is designed to make community messaging, collaboration and discovery as smooth and simple as possible. You can easily create, organise and grow your communities, inviting others to join just in one click.": "Gitter topluluk sohbeti için tasarlandı, işbirliği ve keşfetme mümkün olduğunca basit ve pürüzsüz. Topluluğunuzu çok kolay şekilde oluşturabilir, organize edebilir, büyütebilir ve diğer insanları tek tıkla davet edebilirsiniz.",
  "We also provide integrations with GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly. We accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "GitHub, Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty & Sprintly ile entegrasyonlar sağlıyoruz. Özel web kancalarını kabul ediyoruz. Entegrasyonlar için <a %s>açık kaynaklı depomuz</a>un yanısıra <a %s>esnek API</a>ımız var.",

  "Loved by our users": "Kullanıcılarımız tarafından sevildi",
  "Gitter is nothing without the people using it day in and day out.": "İnsanlar Gitter'i tüm gün kullanmasa Gitter olamazdı.",
  "We asked a few people what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "İnsanlara Gitter'in onlar için ne ifade ettiğini sorduk, bunları söylediler. Eğer Gitter'i sevdiyseniz bize tweet atın <a %s>%s</a>, buradaki mesajları her ay güncelleyeceğiz.",

  "Pricing plans are coming early 2017. Join the Earlybird programme now and get a 75%% discount.": "Ödeme planları 2017 başında uygulanmaya başladı. Şimdi erken erişim programına katılın ve 75%% indirim kazanın.",
  "Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "Ücretler KDV'ye dahil olabilir. Giriş yaparak <a %s>şart ve koşulları</a> kabul etmiş olursunuz.",
  "Free": "Ücretsiz",
  "Forever": "Sonsuza dek",
  "<b>Unlimited</b> chat history": "<b>Sınırsız</b> sohbet geçmişi",
  "<b>Unlimited</b> integrations": "<b>Sınırsız</b> entegrasyon",
  "<b>Unlimited</b> public rooms": "<b>Sınırsız</b> herkese açık oda",
  "<b>Unlimited</b> private rooms": "<b>Sınırsız</b> gizli oda",
  "Limited to 25 users per private room": "Özel odalar 25 kullanıcı ile sınırlıdır",
  "<b>Get started</b> for free": "Ücretsiz <b>başlayın</b>",
  "Premium Plans": "Premium Planlar",
  "starting from": "başlangıç",
  "per month": "aylık",
  "Community <b>insights</b> & analytics": "Topluluk <b>anlayışı</b> ve analitiği",
  "Community <b>engagement</b> & marketing tools": "Topluluk <b>sözleşmesi</b> ve pazarlama araçları",
  "<b>Customisable look</b> of the community rooms": "Topluluk odaları için <b>özelleştirilebilir görünüm</b>",
  "<b>PR & promotional</b> tools": "<b>PR ve promosyon</b> araçları",
  "Access to <b>community managers</b>": "<b>Topluluk yöneticilerine ulaşın</b>",
  "<b>Join</b> earlybird programme": "Erken erişim programına <b>katılın</b>",

  "Get Gitter now!": "Gitter'i şimdi indirin!",
  "Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter tüm modern tarayıcılar, masaüstü ve mobil cihazlar için mevcut.",
  "We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "OSX, iOS, Android, Windows ve Linux uygulamaları mevcut. Ayrıca küçük tatlı bir <a %s>IRC kanalımız</a> var.",
  "Mac": "Mac",
  "Windows": "Windows",
  "Linux 32": "Linux 32",
  "Linux 64": "Linux 64",
  "iPhone": "iPhone",
  "Android": "Android"
}
