{
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Місце, де спілкуються розробники",
	"Integrations": "Інтеграція",
	"Pricing": "Тарифи",
	"Apps": "Додатки",
	"Existing user login": "Вхід для користувачів",
	"login": "вхід",
	"Chat, for GitHub.": "Чат для GitHub",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $5 per user per month. No credit card required.": "В нас розміщені тисячі публічних чатів, в яких розробники з усього світу обговорюють майбутнє програмування, створюють чудові продукти і діляться найкращими картинками котиків.",
	"Sign up free with Github": "Зареєструйтеся через GitHub",
	"Sign up with Github": "Зареєструйстеся через GitHub",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "<a %s>Реєструючись, Ви погоджуєтеся з умовами користувацької угоди.</a>",
	"Markdown power": "Markdown",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "Ви завжди мріяли про повну підтримку markdown в чаті? А як щодо підсвітки синтаксису?",
	"Yip, we got your back.": "Звісно вони є в нас!",
	"Private conversations": "Приватні чати",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "Відкриті кімнати - чудові (і безкоштовні), але деякі речі є конфіденційними. <a %s>В нас є засоби і для цього</a>.",
	"Developer friendly": "Для розробників",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "Це картинка хмарки на фоні хмар. Це перемога! <a %s>Ми інтегруємося</a> з великою кількістю хмарних продуктів.",
	"Some of our communities": "Деякі з наших спільнот",
	"Create your own": "Створи власне",
	"Explore rooms": "досліджувати",
	"Explore": "досліджувати",
	"Integrated with your workflow": "Інтегрований з вашим робочим процесом",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter створений на основі GitHub і добре інтегрується з Вашими репозиторіями, баг-трекерами і активностями.",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.":"Ми надаємо інтеграцію з Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty і Sprintly. Ми також використовуємо користувацькі webhook-и, маємо <a %s>open source репозиторії</a> для інтеграцій, а також надаємо<a %s>гнучке API</a>.",
	"Loved by our users": "Обожнюваний нашими користувачами",
	"Gitter is nothing without the people using it day in and day out.": "Gitter - ніщо, без користувачів, які використовують його щодня.",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.":"Ми запитали деяких користувачів, що для них означає Gitter і ось що вони сказали. Якщо Вам подобається Gitter, пишіть про це в наш Tiwtter <a %s>%s</a> і ми будемо оновлювати ці повідомлення щомісяця.",
	"Personal pricing": "Для персонального використання",
	"Free": "Безкоштовний",
	"Forever": "Назавжди",
	"<b>Unlimited</b> public rooms": "<b>Необмежена</b> кількість публічних кімнат",
	"<b>1</b> private room": "<b>1</b> приватна кімната",
	"<b>2 weeks’</b> chat history": "Історія чату за <b>2 тижні</b>",
	"<b>Get started</b> for free": "<b>Почніть безкоштовно</b>",
	"Individual": "Індивідуальний",
	"monthly": "Місячний",
	"<b>Unlimited</b> private rooms": "<b>Необмежена</b> кількість публічних кімнат",
	"<b>Unlimited</b> chat history": "<b>Необмежена</b> кількість приватних кімнат",
	"<b>Purchase</b> now": "<b>Купіть</b> зараз",
	"Organisation pricing": "Для організацій",
	"Bronze": "Бронза",
	"per user/month": "За користувача в місяць",
	"<b>6 months’</b> chat history": "Історія чату за <b>6 місяців</b>",
	"Silver": "Срібло",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Наш безкоштовний план включає одну приватну кімнату для організації, в яку Ви входите на GitHub",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Наш індивідуальний план дозволяє Вам створювати власні приватні кімнати, використовуючи Ваш обліковий запис",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Наші плани для організацій дозволяють Вам створювати приватні кімнати, власником яких буде Ваша організація на GitHub",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "<a %s>Реєструючись, Ви погоджуєтеся з умовами користувацької угоди.</a>",
	"Get Gitter now!": "Приєднуйтеся до Gitter зараз!",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter доступний у всіх сучасних браузерах, так само як і для мобільних пристроїв та персональних комп’ютерів",
	"We currently have apps for OSX, iOS, Android, Windows and Linux. We also have a sweet little <a %s>IRC bridge</a>": "В нас є додатки для OSX, iOS, Android, Windows i Linux. Ми також маємо милий <a %s>IRC-міст</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Linux 32": "Linux 32",
	"Linux 64": "Linux 64",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "Від розробників для розробників",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter створений в Лондоні командою таких же розробників, як Ви. Чорт забирай, навіть менеджер писав код, правда ми зазвичай переписували ці частини.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "Якщо Ви колись будете пробігати біля Silicon Roundabout, гукніть нам, ми обожнюємо зустрічі з іншими розробниками",
	"Support": "Підтримка",
	"API": "API",
	"Blog": "Блог",
	"Twitter": "Twitter",
	"Translated By": "Dmytro Bezuh"
}
