{
	"Integrations": "集成",
	"Pricing": "价格",
	"Apps": "APP",
	"Existing user login": "已注册用户登录",
	"login": "登录",
	"Chat, for GitHub.": "交流，关于 GitHub。",
	"Get unlimited public rooms and one-to-one chats, free forever. Private team plans start from $2 per user per month. No credit card required.": "即刻获得无限制的公共聊天室和一对一交流，永久免费！私有小组套餐每月5美元起。无需信用卡。",
	"Sign up free with Github": "使用 Github 免费注册",
	"Sign up with Github": "使用 Github 注册",
	"By signing up you agree to our <a %s>Terms and Conditions</a>": "注册即表示同意我们的<a %s>服务条款和隐私政策</a>",
	"Markdown power": "支持 Markdown",
	"Ever wanted full markdown support in chat? How about syntax highlighting?": "想要在聊天中获得完整的 Markdown 支持？语法高亮怎么样？",
	"Yip, we got your back.": "嘿，咱都支持。",
	"Private conversations": "私聊",
	"Public rooms are awesome (and free), but we get that some stuff is private. So we've got <a %s>plans for that</a>.": "公共聊天室特棒（还免费），但我们知道某些事需要私下说。所以，我们推出了<a %s>私聊套餐</a>。",
	"Developer friendly": "开发者友好",
	"This is a picture of a cloud against a background of clouds. OMG! We <a %s>integrate</a> with a bunch of stuff in the cloud.": "这是一朵云的图片，和背景中的云无关。哦对，我们把一堆东西<a %s>集成</a>到云服务中了！",
	"Some of our communities": "Gitter上的部分社区",
	"Create your own": "创建你的社区",
	"Explore rooms": "探索聊天室",
	"Explore": "探索",
	"Integrated with your workflow": "集成到你的工作流程",
	"Gitter is built on top of GitHub and is tightly integrated with your organisations, repositories, issues and activity.": "Gitter 基于 Github 进行构建，紧密地集成到你的 organisations, repositories, issues 和 activity 。",
	"We provide integrations with Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty &amp; Sprintly. We also accept custom webhooks, have an <a %s>open source repository</a> for integrations as well as a <a %s>flexible API</a>.": "我们还提供与 Trello, Jenkins, Travis CI, Heroku, Sentry, BitBucket, HuBoard, Logentries, Pagerduty 以及 Sprintly 的集成。我们同样支持自定义的 webhook ，为集成提供了<a %s>开源库</a>以及<a %s>灵活的API</a>。",
	"Loved by our users": "为用户所喜爱",
	"Gitter is nothing without the people using it day in and day out.": "如果没有大家的支持，Gitter 什么也不是。",
	"We asked a few what Gitter means to them, this is what they had to say. If you love Gitter, Tweet us <a %s>%s</a> and we'll update these quotes every month.": "我们采访了一些用户，Gitter 对他们意味着什么，这里是他们的话。如果你也喜欢Gitter，在Twitter上<a %s>%s</a>，我们每个月都会更新这些留言。",
	"Personal pricing": "个人定价",
	"Free": "免费",
	"Forever": "永久",
	"<b>Unlimited</b> public rooms": "<b>无限制的</b> 公共聊天室",
	"<b>1</b> private room": "<b>1</b> 私有聊天室",
	"<b>2 weeks’</b> chat history": "<b>2 周’</b> 聊天记录",
	"<b>Get started</b> for free": "免费 <b>开始使用</b>",
	"Individual": "个人的",
	"monthly": "每月的",
	"<b>Unlimited</b> private rooms": "<b>无限制的</b> 私有聊天室",
	"<b>Unlimited</b> chat history": "<b>无限制的</b> 聊天记录",
	"<b>Purchase</b> now": "立即<b>购买</b>",
	"Organisation pricing": "团队定价",
	"Bronze": "青铜",
	"per user/month": "每 人/月",
	"<b>6 months’</b> chat history": "<b>6 个月’</b> 聊天记录",
	"Silver": "白银",
	"Our free plan includes one private room per organisation you belong to on GitHub": "Our free plan includes one private room per organisation you belong to on GitHub",
	"Our Individual plan allows you to create private rooms using your personal account as the owner": "Our Individual plan allows you to create private rooms using your personal account as the owner",
	"Our organisation plans allow you to create private rooms using your GitHub organisation as the owner": "Our organisation plans allow you to create private rooms using your GitHub organisation as the owner",
	"Prices may be subject to VAT. By signing up you agree to our <a %s>Terms and Conditions</a>.": "价格可能会受到增值税影响。注册即表示同意我们的<a %s>服务条款和隐私政策</a>。",
	"Get Gitter now!": "即刻获取 Gitter ！",
	"Gitter is available in all modern browsers as well as apps for desktops and mobile phones.": "Gitter 支持所有现代浏览器，并为桌面设备和移动电话提供了应用程序。",
	"We currently have apps for OSX, iOS, Android and Windows with a Linux app coming soon. We also have a sweet little <a %s>IRC bridge</a>": "当前，我们为OSX, iOS, Android, Windows 和 Linux 提供了应用程序。我们还有一款小巧可爱的 <a %s>IRC bridge</a>",
	"Mac": "Mac",
	"Windows": "Windows",
	"Coming soon": "Coming soon",
	"iPhone": "iPhone",
	"Android": "Android",
	"By developers, for developers": "By developers, for developers",
	"Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.": "Gitter is built in London by a team of developers just like you. Hell even the product guy writes code, although we generally end up rewriting those bits.",
	"If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.": "If you're ever around Silicon Roundabout, give us a shout, we love meeting up with other developers.",
	"Support": "Support",
	"API": "API",
	"Blog": "Blog",
	"Twitter": "Twitter",
	"Gitter &mdash; Where developers come to talk.": "Gitter &mdash; Where developers come to talk.",
	"Translated By": "-"
}
